services:
  - type: web
    name: career-bridge
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn cvassistant.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: SERVE_MEDIA
        value: true
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: career-bridge-db
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false

databases:
  - name: career-bridge-db
    plan: free
    databaseName: career_bridge
    user: career_bridge_user
